import { fileURLToPath as __f } from 'node:url';
import { dirname as __d, resolve as __r } from 'node:path';
const __DIR = __d(__f(import.meta.url));
const __REPO = __r(__DIR, '../..');
// Generates src/data/archetypeCompatibilityCandidate.js from the validated
// merged_cells.json. Deterministic: rule ids sorted, archetype order fixed,
// set-like arrays already sorted by the assembler. The module is zero-import
// (Node-clean, mirrors archetypeRuleCompatibility.js) so the api/ test import is
// the BUILD_RULES §4 dependency-surface guard, and Invariant R (never imported
// by fenced/projection/prompt paths) extends to it by construction.
import { readFileSync, writeFileSync } from 'node:fs';

const DIR = __DIR;
const OUT = `${__REPO}/src/data/archetypeCompatibilityCandidate.js`;
const ARCHES = ['momentum_chaser', 'contrarian', 'degen', 'guardian', 'analyst'];
const merged = JSON.parse(readFileSync(`${DIR}/merged_cells.json`, 'utf8'));

function j(v) { return JSON.stringify(v); }
function emitCell(c) {
  // fixed key order so the emitted source is stable
  return `{ state: ${j(c.state)}, rulingIds: ${j(c.rulingIds)}, advisory: ${j(c.advisory)}, `
    + `narrowedParams: ${j(c.narrowedParams)}, displayReason: ${j(c.displayReason)}, notes: ${j(c.notes)} }`;
}

let cells = '';
for (const ruleId of Object.keys(merged).sort()) {
  cells += `  ${j(ruleId)}: {\n`;
  for (const a of ARCHES) {
    const c = merged[ruleId][a];
    if (c) cells += `    ${a}: ${emitCell(c)},\n`;
  }
  cells += `  },\n`;
}

const header = `// src/data/archetypeCompatibilityCandidate.js
//
// Composition Build (PR 1) — the CANDIDATE authored cell-matrix registry.
// Installs the authored rule x archetype compatibility cells as a CANDIDATE
// (spec §3): a new module consumed by NO production path in this PR. It does
// NOT touch the production identity chain, identityHash snapshot, or lock
// (acceptance A22). Activation is a later event (PR 4).
//
// GENERATED by scripts/composition/ (assemble.mjs -> generate_module.mjs) from the seven accepted
// CELL_BATCH ledgers (docs/CELL_BATCH_C1..C7_*.md), transcribed cell-by-cell and
// tally-verified against each batch's own count (see the §9 manifest,
// archetypeCompatibilityCandidate.manifest.json). Do not hand-edit cells;
// regenerate via scripts/composition/ (see its README).
//
// SHAPE (spec §1 cell schema): each (ruleId x archetype) cell is
//   { state, rulingIds, advisory, narrowedParams, displayReason, notes }
//   - state ∈ CANDIDATE_COMPAT_STATES
//   - rulingIds: sorted ADJUDICATION_RULINGS ids (R-xx) governing the cell
//   - advisory: verbatim governed guidance sentence, REQUIRED iff state==='tension'
//   - narrowedParams: null | Domain | { [paramKey]: Domain }, Domain ∈
//       {min,max} | {allow:[...]} | {minOnly:x}
//   - displayReason: the one-line reason of record, REQUIRED iff state==='core_conflict'
//   - notes: sorted subset of CANDIDATE_CELL_NOTE_TOKENS
//
// ZERO-IMPORT (Invariant-R pattern): declares no archetype content by reference;
// it is a pure data + helper module.
//
// KNOWN ADVISORY GAP (tracked, not fabricated — BUILD_RULES §3): a set of tension
// cells carry advisory:null because their verbatim guidance lives in a source not
// committed to the repo (the 35 "unchanged" C7 cells whose advisory of record is
// in the uncommitted C7 V1.0 — CELL_BATCH_C7_FINAL_V1.md:7 defers them to V1.0 —
// plus 2 C2 cells the C2 ledger left without an authored sentence). These are
// enumerated in the manifest's knownAdvisoryGap and asserted by the completeness
// check; the registry is NOT activation-ready until they are supplied. See the
// PR body / docs backlog.

export const CELL_SCHEMA_VERSION = 1;

// §0 source-of-truth sets. INCLUDED_RULES is DERIVED (corpus ∩ ruleSupportStatus
// offerable) by the completeness check, never hardcoded here.
export const INCLUDED_ARCHETYPES = ${j(ARCHES)};
export const RESERVED_ARCHETYPES = ['diversifier'];
export const CANDIDATE_COMPAT_STATES = ['native', 'neutral', 'tension', 'core_conflict', 'deferred'];
export const CANDIDATE_CELL_NOTE_TOKENS = ['prose_only', 'c21_discretionary', 'board_blind', 'weight_only_construction', 'equal_weight_scope'];

/**
 * The authored cell matrix, keyed [ruleId][archetype]. Every offerable
 * ruleId x launch archetype coordinate carries an EXPLICIT cell (spec B1:
 * deferred is an explicit 'deferred' state, never absence).
 */
export const CANDIDATE_COMPAT_CELLS = {
${cells}};

/** The one candidate read surface. Returns the cell or null for an unknown coordinate. */
export function getCandidateCompatCell(ruleId, archetype) {
  const row = CANDIDATE_COMPAT_CELLS[ruleId];
  return (row && row[archetype]) || null;
}

/**
 * Adapter (spec §3 / Phase 0 item 1): map an authored cell into the shape the
 * dark Phase-2 compiler reads (compileBuild.js compatCells contract:
 * { state, via, treatment?, zone1Ref?, tensionReason? }). Every authored cell is
 * EXPLICIT, so via is never 'fallthrough'. advisory/narrowedParams are carried
 * as forward fields the compiler does not read yet (the new compiled fields are
 * PR 3 work per the closure sheet); a 'deferred' state is likewise net-new
 * compiler vocabulary (PR 3). NOT wired into any production read in PR 1.
 */
export function toCompilerCompatCell(cell) {
  if (!cell) return null;
  return {
    state: cell.state,
    via: 'authored',
    ...(cell.state === 'tension' ? { treatment: 'advisoryDowngrade' } : {}),
    zone1Ref: null,
    tensionReason: cell.state === 'core_conflict' ? cell.displayReason : null,
    // forward fields (PR 3 compiled-field work reads these):
    advisory: cell.advisory ?? null,
    narrowedParams: cell.narrowedParams ?? null,
  };
}

/**
 * rulingIndex (minimal, per R2-N2): ruling id -> the coordinates it governs.
 * Derived from the cells so it can never drift from them.
 */
export function buildRulingIndex() {
  const idx = {};
  for (const [ruleId, row] of Object.entries(CANDIDATE_COMPAT_CELLS)) {
    for (const [archetype, cell] of Object.entries(row)) {
      for (const rid of cell.rulingIds || []) {
        (idx[rid] ||= []).push({ ruleId, archetype });
      }
    }
  }
  return idx;
}
`;

writeFileSync(OUT, header);
const cellCount = Object.values(merged).reduce((n, row) => n + Object.keys(row).length, 0);
console.log(`wrote ${OUT}: ${Object.keys(merged).length} rules, ${cellCount} cells, ${header.length} chars`);
