#!/usr/bin/env node
/**
 * Builds stockIntelligenceData.js from:
 *   - Knowledge packages (project files, Tier 1)
 *   - Ledger extracts (Tier 1)
 *   - Deep research extracts (Tier 2)
 *
 * Three-tier context architecture:
 *   Quick Mode: knowledgePackage + ledgerExtract + EODHD real-time data (~5.7-7K tokens/stock)
 *   Deep Mode:  Quick Mode + deepResearch (~8.1-10.1K tokens/stock)
 *   (Tier 3 future: full Gemini reports for cross-company analysis)
 *
 * Run: node buildStockData.js
 * Output: stockIntelligenceData.js (importable ES module)
 */
const fs = require('fs');
const TICKERS = ['NVDA', 'AAPL', 'MSFT', 'AMZN', 'META', 'GOOGL', 'TSLA', 'AMD', 'AVGO', 'SNOW'];
const STOCK_META = {
  NVDA: { name: 'NVIDIA Corporation', shortName: 'NVIDIA', sector: 'Semiconductors', fyEnd: 'Late January' },
  AAPL: { name: 'Apple Inc.', shortName: 'Apple', sector: 'Consumer Electronics', fyEnd: 'Late September' },
  MSFT: { name: 'Microsoft Corporation', shortName: 'Microsoft', sector: 'Software / Cloud', fyEnd: 'June 30' },
  AMZN: { name: 'Amazon.com Inc.', shortName: 'Amazon', sector: 'E-Commerce / Cloud', fyEnd: 'December 31' },
  META: { name: 'Meta Platforms Inc.', shortName: 'Meta', sector: 'Social Media / Advertising', fyEnd: 'December 31' },
  GOOGL: { name: 'Alphabet Inc.', shortName: 'Alphabet', sector: 'Search / Cloud', fyEnd: 'December 31' },
  TSLA: { name: 'Tesla Inc.', shortName: 'Tesla', sector: 'Automotive / Energy', fyEnd: 'December 31' },
  AMD: { name: 'Advanced Micro Devices Inc.', shortName: 'AMD', sector: 'Semiconductors', fyEnd: 'Late December' },
  AVGO: { name: 'Broadcom Inc.', shortName: 'Broadcom', sector: 'Semiconductors / Software', fyEnd: 'Early November' },
  SNOW: { name: 'Snowflake Inc.', shortName: 'Snowflake', sector: 'Cloud Data Platform', fyEnd: 'January 31' },
};
const PROJECT_DIR = '/mnt/project';
const OUTPUTS_DIR = '/mnt/user-data/outputs';
function readFile(path) {
  return fs.existsSync(path) ? fs.readFileSync(path, 'utf8') : '';
}
const stockData = {};
for (const ticker of TICKERS) {
  const knowledgePackage = readFile(`${PROJECT_DIR}/${ticker}_knowledge_package.md`);
  const ledgerExtract = readFile(`${OUTPUTS_DIR}/${ticker}_ledger_extract.md`);
  const deepResearch = readFile(`${OUTPUTS_DIR}/${ticker}_deep_research.md`);
  if (!knowledgePackage) console.warn(`WARNING: Missing knowledge package for ${ticker}`);
  if (!ledgerExtract) console.warn(`WARNING: Missing ledger extract for ${ticker}`);
  if (!deepResearch) console.warn(`WARNING: Missing deep research extract for ${ticker}`);
  stockData[ticker] = {
    ...STOCK_META[ticker],
    ticker,
    knowledgePackage,
    ledgerExtract,
    deepResearch,
  };
}
// Build the output JS module
const output = `// Auto-generated by buildStockData.js — ${new Date().toISOString().split('T')[0]}
// Three-tier context architecture for ${TICKERS.length} stocks.
//
// Tier 1 (Quick Mode): knowledgePackage + ledgerExtract + real-time data
// Tier 2 (Deep Mode):  Tier 1 + deepResearch
//
// Usage:
//   import { STOCK_DATA, getStockContext, TICKERS } from './stockIntelligenceData';
//
//   // Quick Mode (default) — ~5.7-7K tokens
//   const quickCtx = getStockContext('NVDA', eohdDataString);
//
//   // Deep Mode — ~8.1-10.1K tokens
//   const deepCtx = getStockContext('NVDA', eohdDataString, { mode: 'deep' });
//
//   // Access individual pieces
//   const nvda = STOCK_DATA.NVDA;
//   console.log(nvda.knowledgePackage); // Full markdown text
//   console.log(nvda.ledgerExtract);    // Ledger extract text
//   console.log(nvda.deepResearch);     // Deep research extract text
export const TICKERS = ${JSON.stringify(TICKERS)};
export const STOCK_DATA = ${JSON.stringify(stockData, null, 2)};
/**
 * Assembles the context string for a single-stock Haiku API call.
 *
 * @param {string} ticker - Stock ticker (e.g., 'NVDA')
 * @param {string} realtimeData - Formatted EODHD data string (price, RSI, MAs, etc.)
 * @param {Object} [options]
 * @param {'quick'|'deep'} [options.mode='quick'] - Context tier:
 *   'quick': knowledge package + ledger extract + real-time data (~5.7-7K tokens)
 *   'deep':  quick + deep research extract (~8.1-10.1K tokens)
 * @returns {string} Full context string to include in the Haiku system/user message
 */
export function getStockContext(ticker, realtimeData = '', options = {}) {
  const { mode = 'quick' } = options;
  const stock = STOCK_DATA[ticker];
  if (!stock) {
    throw new Error(\`Unknown ticker: \${ticker}. Available: \${TICKERS.join(', ')}\`);
  }
  let context = stock.knowledgePackage;
  if (stock.ledgerExtract) {
    context += '\\n\\n---\\n\\n' + stock.ledgerExtract;
  }
  if (mode === 'deep' && stock.deepResearch) {
    context += '\\n\\n---\\n\\n' + stock.deepResearch;
  }
  if (realtimeData) {
    context += '\\n\\n---\\n\\n## REAL-TIME MARKET DATA\\n' + realtimeData;
  }
  return context;
}
/**
 * Returns metadata for a stock without the full text content.
 * Useful for UI rendering (stock lists, cards, etc.)
 *
 * @param {string} ticker
 * @returns {{ ticker, name, shortName, sector, fyEnd }}
 */
export function getStockMeta(ticker) {
  const stock = STOCK_DATA[ticker];
  if (!stock) return null;
  const { knowledgePackage, ledgerExtract, deepResearch, ...meta } = stock;
  return meta;
}
/**
 * Returns estimated token counts for a stock's context layers.
 * Useful for debugging and cost estimation.
 *
 * @param {string} ticker
 * @returns {{ quick: number, deep: number }}
 */
export function getTokenEstimate(ticker) {
  const stock = STOCK_DATA[ticker];
  if (!stock) return null;
  const quickTokens = Math.round((stock.knowledgePackage.length + stock.ledgerExtract.length + 200) / 4);
  const deepTokens = quickTokens + Math.round(stock.deepResearch.length / 4);
  return { quick: quickTokens, deep: deepTokens };
}
`;
fs.writeFileSync('/home/claude/stockIntelligenceData.js', output, 'utf8');
// Summary
console.log('\\n=== Build Complete ===');
console.log(`Stocks bundled: ${TICKERS.length}`);
const totalSize = Buffer.byteLength(output, 'utf8');
console.log(`Output file size: ${(totalSize / 1024).toFixed(1)} KB`);
console.log(`Estimated total tokens (all stocks, all tiers): ~${Math.round(totalSize / 4)}`);
console.log('\\nPer-stock context sizes:');
console.log('  Ticker  | Quick Mode      | Deep Mode       | Deep Research');
console.log('  --------|-----------------|-----------------|-------------');
for (const t of TICKERS) {
  const s = stockData[t];
  const quickBytes = s.knowledgePackage.length + s.ledgerExtract.length + 200;
  const deepBytes = quickBytes + s.deepResearch.length;
  const drBytes = s.deepResearch.length;
  const qTok = Math.round(quickBytes / 4);
  const dTok = Math.round(deepBytes / 4);
  const drTok = Math.round(drBytes / 4);
  console.log(`  ${t.padEnd(8)}| ~${String(qTok).padEnd(5)} tok (${(qTok/200000*100).toFixed(1)}%) | ~${String(dTok).padEnd(5)} tok (${(dTok/200000*100).toFixed(1)}%) | ~${drTok} tok`);
}
const avgQuick = TICKERS.reduce((sum, t) => {
  const s = stockData[t];
  return sum + s.knowledgePackage.length + s.ledgerExtract.length + 200;
}, 0) / TICKERS.length;
const avgDeep = TICKERS.reduce((sum, t) => {
  const s = stockData[t];
  return sum + s.knowledgePackage.length + s.ledgerExtract.length + s.deepResearch.length + 200;
}, 0) / TICKERS.length;
console.log(`\\n  Average Quick Mode: ~${Math.round(avgQuick/4)} tokens (${(avgQuick/4/200000*100).toFixed(1)}% of 200K window)`);
console.log(`  Average Deep Mode:  ~${Math.round(avgDeep/4)} tokens (${(avgDeep/4/200000*100).toFixed(1)}% of 200K window)`);
console.log(`\\nOutput: /home/claude/stockIntelligenceData.js`);
