// api/_utils/dailyRegimeBriefPrompt.js
// Prompt builder + Anthropic tool schema for the once-daily regime brief.
//
// The brief is generated by Sonnet and injected verbatim into Gemma's
// Voice Layer Block 3.5 via anchorContext. It is forward-looking synthesis
// only — current regime / breadth / sector data is rendered by other blocks.

// =============================================================================
// Anthropic tool schema — forced structured output
// =============================================================================

export const DAILY_REGIME_BRIEF_TOOL = {
  name: 'submit_daily_regime_brief',
  description:
    'Submit the daily regime brief. Returns three fields: a short desk-briefing paragraph (the brief itself, 150-300 tokens), a list of key events to watch this week, and a list of active market themes.',
  input_schema: {
    type: 'object',
    properties: {
      brief: {
        type: 'string',
        description:
          'Desk-briefing paragraph for the trading agent. Forward-looking synthesis of what to watch this week. 150-300 tokens. Do NOT restate current regime/breadth/sector data (other blocks handle that). Never cite VIX levels (not tracked in this system — volatility tier only).',
      },
      keyEvents: {
        type: 'array',
        description: '3-6 most consequential scheduled events this week. Pick from the calendars provided in user prompt; do not invent events.',
        items: {
          type: 'object',
          required: ['label', 'eventDate', 'kind', 'whyItMatters', 'tickers'],
          properties: {
            label: {
              type: 'string',
              description: 'Short event name. Examples: "Fed rate decision", "NVDA earnings", "CPI release", "Q1 GDP advance". 3-6 words.',
            },
            eventDate: {
              type: 'string',
              description: 'YYYY-MM-DD date of the event, copied directly from the calendar input.',
            },
            eventTime: {
              type: 'string',
              description: 'Time of day. Examples: "2:00 PM ET", "AMC", "BMO", "8:30 AM ET". Empty string if not applicable.',
            },
            kind: {
              type: 'string',
              enum: ['macro', 'earnings', 'fed', 'speech', 'auction'],
              description: 'Event category. macro = CPI/GDP/PMI/etc. earnings = company earnings. fed = FOMC decisions. speech = Fed/policymaker speeches. auction = Treasury auctions.',
            },
            whyItMatters: {
              type: 'string',
              description: '1-2 sentences explaining what to watch and why it matters for positioning. Desk-briefing voice. ~140 characters max.',
            },
            tickers: {
              type: 'array',
              items: { type: 'string' },
              description: '2-3 affected tickers. For earnings, the company itself. For macro/fed events, broad-market tickers most reactive (SPY, TLT, GLD, DXY, XLE, etc.). Pick from US-listed names.',
            },
          },
        },
      },
      themes: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Short list (2-5 items) of active market themes informing this week\'s setup. Each item a compact noun phrase, e.g. "AI capex rotation cooling" or "rates repricing on sticky services inflation".',
      },
    },
    required: ['brief', 'keyEvents', 'themes'],
  },
};

// =============================================================================
// System prompt — injected into every DRB call
// =============================================================================

const SYSTEM_PROMPT = `You are generating a daily regime brief for FantasyTrades, a competitive trading game. The brief will be injected into a trading agent's system prompt. The agent talks casually with users about market strategy and needs forward-looking context about what to watch this week.

MANDATORY CONSTRAINTS:
- VIX is not tracked in this system. Refer to volatility tiers only (elevated/normal/compressed). Never cite VIX levels, numbers, or ranges.
- Do NOT restate current regime data (regime name, breadth tiers, sector movers) — separate systems inject that context elsewhere in the agent's prompt.
- Your output is FORWARD-LOOKING synthesis: this week's calendar, active themes, what-to-watch framing.
- Desk-briefing voice: direct, specific, informed. Not marketing copy. Not a news summary.
- Keep the brief 150-300 tokens. Tight is better than long.
- Your output will be injected verbatim into another model's context. Help the agent sound sharper, not longer.
- For each keyEvent, copy the eventDate verbatim from the calendar input. Do not infer or guess dates.
- Tickers must be US-listed and trade-able. For macro/fed events, pick the 2-3 most reactive broad-market or sector ETFs (SPY, TLT, GLD, DXY, XLE, XLF, etc.).

You MUST respond via the submit_daily_regime_brief tool. No prose responses outside the tool call.`;

// =============================================================================
// User prompt builder
// =============================================================================

function renderSymbols(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return '(none)';
  return arr.map((s) => `- ${s}`).join('\n');
}

// 3-letter weekday abbreviation. Sonnet's tool schema instructs it to copy
// eventDate verbatim from the calendar input — the YYYY-MM-DD anchors the
// copy; the day abbreviation is a sanity-check tag for the model.
function formatDayShort(dayName) {
  if (typeof dayName !== 'string' || dayName.length < 3) return '';
  return dayName.charAt(0).toUpperCase() + dayName.slice(1, 3).toLowerCase();
}

function renderEconEvents(events, limit = null) {
  if (!Array.isArray(events) || events.length === 0) return '(none)';
  const slice = limit ? events.slice(0, limit) : events;
  return slice
    .map((e) => {
      const date = e?.date || '????-??-??';
      const day = e?.day ? ` (${formatDayShort(e.day)})` : '';
      const time = e?.time ? ` ${e.time}` : '';
      const name = e?.event || 'event';
      const flag = e?.impact === 'high' ? ' [HIGH]' : '';
      return `- ${date}${day}${time} — ${name}${flag}`;
    })
    .join('\n');
}

function renderEconEventsPreview(events, limit = 5) {
  if (!Array.isArray(events) || events.length === 0) return '(none)';
  return events
    .slice(0, limit)
    .map((e) => {
      const date = e?.date || '????-??-??';
      const day = e?.day ? ` (${formatDayShort(e.day)})` : '';
      const name = e?.event || 'event';
      return `- ${date}${day} — ${name}`;
    })
    .join('\n');
}

function renderEarnings(entries, limit = null) {
  if (!Array.isArray(entries) || entries.length === 0) return '(none)';
  const filtered = entries.filter((e) => e?.significance === 'high');
  if (filtered.length === 0) return '(none)';
  const slice = limit ? filtered.slice(0, limit) : filtered;
  return slice
    .map((e) => {
      const date = e?.date || '????-??-??';
      const day = e?.day ? ` (${formatDayShort(e.day)})` : '';
      const timing = e?.timing || '??';
      const symbol = e?.symbol || '???';
      const name = e?.name ? ` (${e.name})` : '';
      return `- ${date}${day} ${timing} — ${symbol}${name}`;
    })
    .join('\n');
}

function renderEarningsPreview(entries, limit = 5) {
  if (!Array.isArray(entries) || entries.length === 0) return '(none)';
  const filtered = entries.filter((e) => e?.significance === 'high');
  if (filtered.length === 0) return '(none)';
  return filtered
    .slice(0, limit)
    .map((e) => {
      const date = e?.date || '????-??-??';
      const day = e?.day ? ` (${formatDayShort(e.day)})` : '';
      const timing = e?.timing || '??';
      const symbol = e?.symbol || '???';
      return `- ${date}${day} ${timing} — ${symbol}`;
    })
    .join('\n');
}

/**
 * buildDailyRegimeBriefPrompt
 *
 * Returns { systemPrompt, userPrompt } ready to pass to anthropic.messages.create.
 * All fields are defensive — missing/undefined inputs coalesce to 'unknown' or (none)
 * so the cron never throws on malformed upstream data.
 *
 * @param {Object} args
 * @param {Object} [args.marketContext]           Firestore indexIntelligence/marketContext doc
 * @param {string[]} [args.technicalLeaders]      Top 5 symbols by technical score
 * @param {string[]} [args.technicalLaggards]     Bottom 5 symbols by technical score
 * @param {Array} [args.thisWeekEvents]           Economic events this week
 * @param {Array} [args.nextWeekEvents]           Economic events next week
 * @param {Array} [args.thisWeekEarnings]         Earnings entries this week
 * @param {Array} [args.nextWeekEarnings]         Earnings entries next week
 * @param {string} args.forDate                   YYYY-MM-DD
 */
export function buildDailyRegimeBriefPrompt({
  marketContext,
  technicalLeaders,
  technicalLaggards,
  thisWeekEvents,
  nextWeekEvents,
  thisWeekEarnings,
  nextWeekEarnings,
  forDate,
}) {
  const mc = marketContext || {};
  const regime = mc.regime || 'unknown';
  const regimeDetail = mc.regimeDetail ? `\n${mc.regimeDetail}` : '';
  const volTier = mc.volatilityRegime || 'unknown';
  const breadth = mc.breadthTier || 'unknown';
  const topSector = mc.topSectorToday || 'unknown';
  const topSectorChg = mc.topSectorChange != null ? `${mc.topSectorChange}%` : 'n/a';
  const worstSector = mc.worstSectorToday || 'unknown';
  const worstSectorChg = mc.worstSectorChange != null ? `${mc.worstSectorChange}%` : 'n/a';

  const userPrompt = `Date: ${forDate}

=== CURRENT MARKET CONTEXT (for reference; do not restate) ===
Regime: ${regime}${regimeDetail}
Volatility tier: ${volTier}
Breadth: ${breadth}
Top sector today: ${topSector} (${topSectorChg})
Worst sector today: ${worstSector} (${worstSectorChg})

=== TECHNICAL LEADERS (top 5) ===
${renderSymbols(technicalLeaders)}

=== TECHNICAL LAGGARDS (bottom 5) ===
${renderSymbols(technicalLaggards)}

=== ECONOMIC CALENDAR — THIS WEEK ===
${renderEconEvents(thisWeekEvents)}

=== ECONOMIC CALENDAR — NEXT WEEK (preview) ===
${renderEconEventsPreview(nextWeekEvents, 5)}

=== EARNINGS — THIS WEEK (mega-cap only) ===
${renderEarnings(thisWeekEarnings)}

=== EARNINGS — NEXT WEEK (preview) ===
${renderEarningsPreview(nextWeekEarnings, 5)}

Synthesize a daily regime brief. Use the submit_daily_regime_brief tool.`;

  return { systemPrompt: SYSTEM_PROMPT, userPrompt };
}
