// api/_utils/dailyRegimeBriefPrompt.js
// Prompt builder + Anthropic tool schema for the once-daily regime brief.
//
// The brief is generated by Sonnet and injected verbatim into Gemma's
// Voice Layer Block 3.5 via anchorContext. It is forward-looking synthesis
// only — current regime / breadth / sector data is rendered by other blocks.

// =============================================================================
// Anthropic tool schema — forced structured output
// =============================================================================

export const DAILY_REGIME_BRIEF_TOOL = {
  name: 'submit_daily_regime_brief',
  description:
    'Submit the daily regime brief. Returns three fields: a short desk-briefing paragraph (the brief itself, 150-300 tokens), a list of key events to watch this week, and a list of active market themes.',
  input_schema: {
    type: 'object',
    properties: {
      brief: {
        type: 'string',
        description:
          'Desk-briefing paragraph for the trading agent. Forward-looking synthesis of what to watch this week. 150-300 tokens. Do NOT restate current regime/breadth/sector data (other blocks handle that). Never cite VIX levels (not tracked in this system — volatility tier only).',
      },
      keyEvents: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Short list (3-6 items) of the most consequential scheduled events this week — Fed prints, earnings, macro releases. Each item one short phrase, e.g. "Wed FOMC decision" or "Thu NVDA earnings AMC".',
      },
      themes: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Short list (2-5 items) of active market themes informing this week\'s setup. Each item a compact noun phrase, e.g. "AI capex rotation cooling" or "rates repricing on sticky services inflation".',
      },
    },
    required: ['brief', 'keyEvents', 'themes'],
  },
};

// =============================================================================
// System prompt — injected into every DRB call
// =============================================================================

const SYSTEM_PROMPT = `You are generating a daily regime brief for FantasyTrades, a competitive trading game. The brief will be injected into a trading agent's system prompt. The agent talks casually with users about market strategy and needs forward-looking context about what to watch this week.

MANDATORY CONSTRAINTS:
- VIX is not tracked in this system. Refer to volatility tiers only (elevated/normal/compressed). Never cite VIX levels, numbers, or ranges.
- Do NOT restate current regime data (regime name, breadth tiers, sector movers) — separate systems inject that context elsewhere in the agent's prompt.
- Your output is FORWARD-LOOKING synthesis: this week's calendar, active themes, what-to-watch framing.
- Desk-briefing voice: direct, specific, informed. Not marketing copy. Not a news summary.
- Keep the brief 150-300 tokens. Tight is better than long.
- Your output will be injected verbatim into another model's context. Help the agent sound sharper, not longer.

You MUST respond via the submit_daily_regime_brief tool. No prose responses outside the tool call.`;

// =============================================================================
// User prompt builder
// =============================================================================

function renderSymbols(arr) {
  if (!Array.isArray(arr) || arr.length === 0) return '(none)';
  return arr.map((s) => `- ${s}`).join('\n');
}

function renderEconEvents(events, limit = null) {
  if (!Array.isArray(events) || events.length === 0) return '(none)';
  const slice = limit ? events.slice(0, limit) : events;
  return slice
    .map((e) => {
      const day = e?.day || e?.date || '???';
      const time = e?.time ? ` ${e.time}` : '';
      const name = e?.event || 'event';
      const flag = e?.impact === 'high' ? ' [HIGH]' : '';
      return `- ${day}${time} — ${name}${flag}`;
    })
    .join('\n');
}

function renderEconEventsPreview(events, limit = 5) {
  if (!Array.isArray(events) || events.length === 0) return '(none)';
  return events
    .slice(0, limit)
    .map((e) => {
      const day = e?.day || e?.date || '???';
      const name = e?.event || 'event';
      return `- ${day} — ${name}`;
    })
    .join('\n');
}

function renderEarnings(entries, limit = null) {
  if (!Array.isArray(entries) || entries.length === 0) return '(none)';
  const filtered = entries.filter((e) => e?.significance === 'high');
  if (filtered.length === 0) return '(none)';
  const slice = limit ? filtered.slice(0, limit) : filtered;
  return slice
    .map((e) => {
      const day = e?.day || e?.date || '???';
      const timing = e?.timing || '??';
      const symbol = e?.symbol || '???';
      const name = e?.name ? ` (${e.name})` : '';
      return `- ${day} ${timing} — ${symbol}${name}`;
    })
    .join('\n');
}

function renderEarningsPreview(entries, limit = 5) {
  if (!Array.isArray(entries) || entries.length === 0) return '(none)';
  const filtered = entries.filter((e) => e?.significance === 'high');
  if (filtered.length === 0) return '(none)';
  return filtered
    .slice(0, limit)
    .map((e) => {
      const day = e?.day || e?.date || '???';
      const timing = e?.timing || '??';
      const symbol = e?.symbol || '???';
      return `- ${day} ${timing} — ${symbol}`;
    })
    .join('\n');
}

/**
 * buildDailyRegimeBriefPrompt
 *
 * Returns { systemPrompt, userPrompt } ready to pass to anthropic.messages.create.
 * All fields are defensive — missing/undefined inputs coalesce to 'unknown' or (none)
 * so the cron never throws on malformed upstream data.
 *
 * @param {Object} args
 * @param {Object} [args.marketContext]           Firestore indexIntelligence/marketContext doc
 * @param {string[]} [args.technicalLeaders]      Top 5 symbols by technical score
 * @param {string[]} [args.technicalLaggards]     Bottom 5 symbols by technical score
 * @param {Array} [args.thisWeekEvents]           Economic events this week
 * @param {Array} [args.nextWeekEvents]           Economic events next week
 * @param {Array} [args.thisWeekEarnings]         Earnings entries this week
 * @param {Array} [args.nextWeekEarnings]         Earnings entries next week
 * @param {string} args.forDate                   YYYY-MM-DD
 */
export function buildDailyRegimeBriefPrompt({
  marketContext,
  technicalLeaders,
  technicalLaggards,
  thisWeekEvents,
  nextWeekEvents,
  thisWeekEarnings,
  nextWeekEarnings,
  forDate,
}) {
  const mc = marketContext || {};
  const regime = mc.regime || 'unknown';
  const regimeDetail = mc.regimeDetail ? `\n${mc.regimeDetail}` : '';
  const volTier = mc.volatilityRegime || 'unknown';
  const breadth = mc.breadthTier || 'unknown';
  const topSector = mc.topSectorToday || 'unknown';
  const topSectorChg = mc.topSectorChange != null ? `${mc.topSectorChange}%` : 'n/a';
  const worstSector = mc.worstSectorToday || 'unknown';
  const worstSectorChg = mc.worstSectorChange != null ? `${mc.worstSectorChange}%` : 'n/a';

  const userPrompt = `Date: ${forDate}

=== CURRENT MARKET CONTEXT (for reference; do not restate) ===
Regime: ${regime}${regimeDetail}
Volatility tier: ${volTier}
Breadth: ${breadth}
Top sector today: ${topSector} (${topSectorChg})
Worst sector today: ${worstSector} (${worstSectorChg})

=== TECHNICAL LEADERS (top 5) ===
${renderSymbols(technicalLeaders)}

=== TECHNICAL LAGGARDS (bottom 5) ===
${renderSymbols(technicalLaggards)}

=== ECONOMIC CALENDAR — THIS WEEK ===
${renderEconEvents(thisWeekEvents)}

=== ECONOMIC CALENDAR — NEXT WEEK (preview) ===
${renderEconEventsPreview(nextWeekEvents, 5)}

=== EARNINGS — THIS WEEK (mega-cap only) ===
${renderEarnings(thisWeekEarnings)}

=== EARNINGS — NEXT WEEK (preview) ===
${renderEarningsPreview(nextWeekEarnings, 5)}

Synthesize a daily regime brief. Use the submit_daily_regime_brief tool.`;

  return { systemPrompt: SYSTEM_PROMPT, userPrompt };
}
