/**
 * Stock Brief Service — Firestore read helper for Tier 2 Sonar briefs.
 *
 * Provides cached access to stockBriefs/{SYMBOL} documents.
 * Used by: api/stocks/analysis.js (Phase 2C, future)
 */

import { initializeApp, getApps, cert } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

// ---------------------------------------------------------------------------
// Firebase Admin
// ---------------------------------------------------------------------------

function getFirebaseAdmin() {
  if (getApps().length === 0) {
    const serviceAccount = {
      projectId: process.env.FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      privateKey: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    };
    initializeApp({ credential: cert(serviceAccount) });
  }
  return getFirestore();
}

// ---------------------------------------------------------------------------
// In-memory cache (5-minute TTL)
// ---------------------------------------------------------------------------

const briefCache = new Map();
const CACHE_TTL = 5 * 60 * 1000;

/**
 * Fetch a Tier 2 stock brief from Firestore (with in-memory caching).
 *
 * @param {string} symbol - Stock ticker (e.g. 'RKLB')
 * @returns {Promise<Object|null>} The brief object, or null if not found/expired
 */
export async function getStockBrief(symbol) {
  // Check memory cache first
  const cached = briefCache.get(symbol);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.data;
  }

  // Fetch from Firestore
  const db = getFirebaseAdmin();
  const doc = await db.collection('stockBriefs').doc(symbol).get();

  if (!doc.exists) return null;

  const data = doc.data();

  // Check if expired
  if (data.expiresAt) {
    const expiresDate = data.expiresAt.toDate ? data.expiresAt.toDate() : new Date(data.expiresAt);
    if (expiresDate < new Date()) {
      return null; // Expired — will be regenerated by next cron run
    }
  }

  // Cache and return the brief
  briefCache.set(symbol, { data: data.brief, timestamp: Date.now() });

  return data.brief;
}
